#!/usr/bin/env bash
# Collect all output from this script to ~/Library/Logs/WiFiLocControl.log
exec 2>&1

# Enable stealth mode which makes your computer less visible to potential attackers
/usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on

# Send a notification indicating that location has changed
# osascript -e 'display notification "Location changed to Automatic" with title "Network Location"'
# Send a dialog indicating that location has changed
osascript -e 'display dialog "Location changed to Automatic" with title "Network Location" buttons {"Accept"} default button 1'